import React from 'react';
import { Link } from 'react-router-dom';

const Metric = ({ value, label }: { value: string; label: string }) => <div className="border-t border-line pt-4"><div className="font-serif text-4xl md:text-5xl text-ink">{value}</div><p className="mt-2 text-[10px] font-semibold uppercase tracking-[.16em] text-muted leading-relaxed">{label}</p></div>;

export const NetworkStory = () => <div className="space-y-28 md:space-y-40 max-w-6xl mx-auto">
  <header className="pt-2 pb-16 border-b border-line">
    <p className="text-xs font-semibold text-[#1565c0] uppercase tracking-[.2em] mb-6">03 — The Network</p>
    <h1 className="max-w-5xl font-serif text-4xl md:text-6xl font-normal text-ink leading-[1.08] uppercase">Who actually supplies whom — and how stable are those relationships?</h1>
    <p className="mt-10 max-w-3xl text-xl font-light leading-relaxed text-body">Before FOODSHIELD removes a supplier, it follows the observed trade relationships that connect importers, suppliers, commodities, and years. This chapter describes that network; it does not yet make a resilience claim.</p>
  </header>

  <section className="grid grid-cols-1 lg:grid-cols-[1.1fr_.9fr] gap-12 lg:gap-20 items-end">
    <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#1565c0] mb-6">The central observation</p><h2 className="font-serif text-5xl md:text-7xl leading-[.95] text-ink">Food trade is a network, not a single supply line.</h2></div>
    <p className="text-lg font-light leading-relaxed text-body border-l-2 border-[#1565c0] pl-6">Across six locked commodities and 2010–2023, FOODSHIELD records 128,486 positive-flow supplier relationships. Each relationship is an observed link, not a promise that it will remain available in another year.</p>
  </section>

  <section className="border-y border-line py-10 md:py-14"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-muted mb-10">Observed network scale · 2010–2023</p><div className="grid grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-12"><Metric value="128,486" label="Positive-flow relationships" /><Metric value="25,497" label="Importer–supplier–commodity systems" /><Metric value="10,229" label="Distinct importer–supplier pairs" /><Metric value="178" label="Importing countries" /><Metric value="197" label="Supplying countries" /><Metric value="14" label="Trade-analysis years" /></div></section>

  <section>
    <div className="max-w-3xl mb-10"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#1565c0] mb-4">Reading the network</p><h2 className="font-serif text-3xl md:text-4xl text-ink">One importer can be connected to several suppliers — with different observed shares.</h2></div>
    <div className="border border-line bg-wash p-5 md:p-10 overflow-x-auto"><div className="flex justify-between gap-4 mb-8 text-[10px] uppercase tracking-[.16em] font-semibold text-muted"><span>Conceptual representation of observed bilateral links</span><span className="hidden sm:inline">Line width indicates relative flow</span></div>
      <svg viewBox="0 0 1000 400" className="w-full min-w-[560px] h-auto" role="img" aria-label="Conceptual food trade network showing an importer connected to suppliers">
        <path d="M470 200 C360 75 280 75 180 75" stroke="#F6DBC0" strokeWidth="7" fill="none"/><path d="M470 200 C350 145 275 150 180 150" stroke="#935073" strokeWidth="18" fill="none"/><path d="M470 200 C350 230 275 235 180 235" stroke="#935073" strokeOpacity=".55" strokeWidth="10" fill="none"/><path d="M470 200 C350 325 280 325 180 325" stroke="#935073" strokeOpacity=".45" strokeWidth="5" fill="none" strokeDasharray="9 9"/><path d="M530 200 C650 130 740 130 850 130" stroke="#F6DBC0" strokeWidth="4" fill="none"/><path d="M530 200 C650 270 740 270 850 270" stroke="#F6DBC0" strokeWidth="4" fill="none"/>
        <rect x="420" y="145" width="160" height="110" rx="3" fill="#502D55"/><text x="500" y="190" textAnchor="middle" fill="#F8F4E9" fontSize="17" fontWeight="600" letterSpacing="2">IMPORTER</text><text x="500" y="216" textAnchor="middle" fill="#F6DBC0" fontSize="12">one commodity · one year</text>
        <g fontSize="13" fontWeight="600" textAnchor="middle"><rect x="30" y="50" width="185" height="48" fill="#F8F4E9" stroke="#F6DBC0"/><text x="122" y="79" fill="#502D55">SUPPLIER A</text><rect x="30" y="125" width="185" height="48" fill="#F6DBC0" stroke="#935073" strokeWidth="2"/><text x="122" y="154" fill="#502D55">LARGEST SUPPLIER</text><rect x="30" y="210" width="185" height="48" fill="#F8F4E9" stroke="#F6DBC0"/><text x="122" y="239" fill="#502D55">SUPPLIER C</text><rect x="30" y="300" width="185" height="48" fill="#F8F4E9" stroke="#F6DBC0"/><text x="122" y="329" fill="#502D55">HISTORICAL LINK</text><text x="850" y="118" fill="#502D55">OTHER OBSERVED LINKS</text><text x="850" y="258" fill="#502D55">NETWORK CONTINUES</text></g>
      </svg>
      <div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 text-xs text-body"><span><i className="inline-block w-8 h-[3px] bg-[#1565c0] align-middle mr-2" />greater observed flow</span><span><i className="inline-block w-8 h-[2px] bg-[#b9c7d5] align-middle mr-2" />other current link</span><span><i className="inline-block w-8 border-t-2 border-dashed border-[#b9c7d5] align-middle mr-2" />historically observed link</span></div>
    </div>
  </section>

  <section className="grid grid-cols-1 lg:grid-cols-[.8fr_1.2fr] gap-12 lg:gap-20"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#1565c0] mb-5">Stability is not assumed</p><h2 className="font-serif text-4xl md:text-5xl text-ink leading-tight">A broad network can still be a moving one.</h2></div><div className="space-y-8"><p className="text-xl font-light leading-relaxed text-body">The typical observed pairing is active for 5.04 years. Average persistence is 35.99%, while median persistence is 21.43%. The network records 34,534 entries and 31,420 exits over the study period.</p><p className="text-lg font-serif leading-relaxed text-ink border-l-4 border-[#e6a817] pl-6">A relationship observed in history is evidence of prior connection — not evidence that it is active, available, or guaranteed in a future shock year.</p></div></section>
  <section className="grid grid-cols-1 md:grid-cols-3 gap-px bg-line border border-line"><div className="bg-paper p-8"><p className="text-[10px] uppercase tracking-[.16em] font-semibold text-muted">Average active years</p><p className="mt-5 font-serif text-5xl text-ink">5.04</p></div><div className="bg-paper p-8"><p className="text-[10px] uppercase tracking-[.16em] font-semibold text-muted">Average persistence</p><p className="mt-5 font-serif text-5xl text-ink">35.99%</p></div><div className="bg-paper p-8"><p className="text-[10px] uppercase tracking-[.16em] font-semibold text-muted">Median persistence</p><p className="mt-5 font-serif text-5xl text-ink">21.43%</p></div></section>

  <section className="bg-ink text-white p-8 md:p-14"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#8fb8e8] mb-5">What this does — and does not — tell us</p><div className="grid grid-cols-1 lg:grid-cols-2 gap-12"><h2 className="font-serif text-3xl md:text-4xl leading-tight">Supplier count is not resilience.</h2><div className="space-y-5 text-lg font-light leading-relaxed text-gray-300"><p>Average supplier count is 10.98, the median is 9, and the maximum observed is 79. These describe the breadth of observed supplier relationships.</p><p>They do not create a threshold, score, or guarantee. Supplier count is distinct from supplier shares, concentration, shock loss, and the later modeled replacement outcome.</p></div></div></section>

  <section className="grid grid-cols-1 md:grid-cols-2 gap-12 border-t border-line pt-14"><div><h2 className="font-serif text-3xl text-ink mb-5">Why history enters the model</h2><p className="text-body font-light leading-relaxed">FOODSHIELD distinguishes suppliers active in the shock year, qualifying historical suppliers absent in that year, and eligible new origins. The distinction preserves the difference between an observed current link and a prior relationship.</p></div><div className="space-y-4 text-sm text-body"><div className="border-l-2 border-[#0e9f6a] pl-5"><strong className="text-ink">Tier 1 — Current suppliers</strong><br/>Active in the shock year.</div><div className="border-l-2 border-[#2bbf8a] pl-5"><strong className="text-ink">Tier 2 — Historical suppliers</strong><br/>Qualifying prior bilateral relationships absent in the shock year.</div><div className="border-l-2 border-[#2a7de1] pl-5"><strong className="text-ink">Tier 3 — New origins</strong><br/>Eligible origins without a qualifying prior bilateral relationship.</div></div></section>
  <section className="text-center py-16 border-y border-line"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-muted mb-5">Network quantity</p><div className="font-serif text-5xl md:text-7xl text-ink">5,124,398,255</div><p className="mt-3 text-xs font-semibold uppercase tracking-[.16em] text-body">Tonnes across the Step 7B analytical network</p><p className="mt-6 max-w-2xl mx-auto text-sm font-light leading-relaxed text-muted">Across Wheat, Rice, Maize, Palm Oil, Sugar, and Sunflower Oil; reconciled to Step 6A bilateral quantity after excluding self-trade and zero/null flows.</p></section>
  <section className="py-24 text-center bg-wash border-t border-line"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#e23b2a] mb-6">Next: the counterfactual</p><h2 className="max-w-3xl mx-auto font-serif text-4xl md:text-5xl leading-tight text-ink">The network maps relationships. The next chapter asks what remains when the dominant supplier is removed.</h2><p className="mt-7 max-w-2xl mx-auto text-body font-light">This is a modeled supplier-shock experiment, not a prediction or guarantee about future trade relationships.</p><Link to="/shock" className="inline-flex items-center justify-center mt-12 px-12 py-5 bg-ink text-white text-sm font-semibold tracking-widest uppercase hover:bg-[#1a365d] transition-colors">Simulate the shock →</Link></section>
</div>;
